apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(':TMessagesProj')
    implementation project(':SnezhokCore')
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}

android {
    namespace 'xyz.merchedits.snezhok.preview'
    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'xyz.merchedits.snezhok.preview'
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName '0.1.0'
        multiDexEnabled true

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        debug {
            debuggable true
            jniDebuggable true
            minifyEnabled false
            shrinkResources false
            multiDexEnabled true
        }
        release {
            minifyEnabled true
            shrinkResources true
            multiDexEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), '../TMessagesProj/proguard-rules.pro'
        }
    }

    variantFilter { variant ->
        if (variant.buildType.name != 'debug') {
            setIgnore(true)
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }

    buildFeatures {
        buildConfig = true
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = 'snezhok-preview.apk'
        }
    }
}
