const copy = {
  ru: {
    accountSecurity: "Аккаунт и устройства", activeSessions: "Активные сеансы", currentDevice: "Это устройство", revoke: "Завершить", revokeOthers: "Завершить другие сеансы", noSessions: "Активных сеансов нет", deleteAccount: "Удалить аккаунт", deleteAccountWarning: "Аккаунт будет обезличен, а доступ со всех устройств закрыт. Это действие необратимо.", enterPassword: "Введите пароль", deletePermanently: "Удалить навсегда",
    privacyDetails: "Конфиденциальность", directMessages: "Личные сообщения", groupInvites: "Приглашения в группы", profilePhotosPrivacy: "Фотографии профиля", everyone: "Все", contactsOnly: "Контакты", nobody: "Никто", blockedUsers: "Заблокированные", noBlockedUsers: "Заблокированных пользователей нет", unblock: "Разблокировать", block: "Заблокировать",
    notifications: "Уведомления", messages: "Сообщения", calls: "Звонки", previews: "Текст сообщения", sound: "Звук", mobileDelivery: "На телефоне", mentionsOnly: "Только упоминания", quietHours: "Тихие часы", quietHoursHint: "22:00–08:00 по времени устройства", quietHoursDays: "Дни недели", sundayShort: "Вс", mondayShort: "Пн", tuesdayShort: "Вт", wednesdayShort: "Ср", thursdayShort: "Чт", fridayShort: "Пт", saturdayShort: "Сб", serverOverrides: "Настройки серверов", chatOverrides: "Настройки чатов", inherit: "Как в общих настройках", enabled: "Включено", disabled: "Выключено", muted: "Без звука", muteOneHour: "На 1 час", reset: "Сбросить",
    mentions: "Упоминания", noMentions: "Вас пока не упоминали", loadMore: "Загрузить ещё",
    groupManagement: "Управление группой", groupName: "Название группы", members: "Участники", addMember: "Добавить участника", owner: "Владелец", administrator: "Администратор", moderator: "Модератор", member: "Участник", makeAdmin: "Назначить администратором", removeAdmin: "Снять администратора", removeMember: "Удалить из группы", transferOwnership: "Передать владельца", leaveGroup: "Покинуть группу", groupPhoto: "Фото группы", selectUsers: "Выберите участников", createGroup: "Создать группу", next: "Далее", selectedCount: "Выбрано: {count}", directChat: "Личный чат",
    serverManagement: "Настройки сервера", overview: "Обзор", categories: "Категории", channels: "Каналы", roles: "Роли", bans: "Блокировки", auditLog: "Журнал действий", permissions: "Разрешения", overrides: "Права канала", addCategory: "Добавить категорию", addChannel: "Добавить канал", addRole: "Добавить роль", textChannel: "Текстовый канал", voiceChannel: "Голосовой канал", edit: "Изменить", delete: "Удалить", kick: "Исключить", ban: "Заблокировать", unban: "Разблокировать", transferServer: "Передать сервер", leaveServer: "Покинуть сервер", deleteServer: "Удалить сервер", serverIcon: "Значок сервера", permissionAllow: "Разрешить", permissionDeny: "Запретить", permissionInherit: "Наследовать", defaultMembers: "Все участники", noItems: "Здесь пока пусто",
    save: "Сохранить", cancel: "Отмена", close: "Закрыть", search: "Поиск", add: "Добавить", confirm: "Подтвердить", operationFailed: "Не удалось выполнить действие", saved: "Сохранено", loading: "Загрузка…", reason: "Причина", name: "Название", userNotFound: "Пользователь не найден", quietHoursStart: "Начало", quietHoursEnd: "Окончание", chooseTime: "Выберите время", openSource: "Открытый код", sourceCode: "Исходный код", legalNotice: "Snezhok — свободное ПО по лицензии GNU GPL 3 или более поздней версии. Программа поставляется без каких-либо гарантий. Исходный код и уведомления о сторонних компонентах доступны в публичном репозитории.",
  },
  en: {
    accountSecurity: "Account and devices", activeSessions: "Active sessions", currentDevice: "This device", revoke: "Terminate", revokeOthers: "Terminate other sessions", noSessions: "No active sessions", deleteAccount: "Delete account", deleteAccountWarning: "Your account will be anonymized and every device signed out. This cannot be undone.", enterPassword: "Enter password", deletePermanently: "Delete permanently",
    privacyDetails: "Privacy", directMessages: "Direct messages", groupInvites: "Group invites", profilePhotosPrivacy: "Profile photos", everyone: "Everybody", contactsOnly: "Contacts", nobody: "Nobody", blockedUsers: "Blocked users", noBlockedUsers: "No blocked users", unblock: "Unblock", block: "Block",
    notifications: "Notifications", messages: "Messages", calls: "Calls", previews: "Message preview", sound: "Sound", mobileDelivery: "Mobile delivery", mentionsOnly: "Mentions only", quietHours: "Quiet hours", quietHoursHint: "22:00–08:00 in device time", quietHoursDays: "Days of week", sundayShort: "Sun", mondayShort: "Mon", tuesdayShort: "Tue", wednesdayShort: "Wed", thursdayShort: "Thu", fridayShort: "Fri", saturdayShort: "Sat", serverOverrides: "Server overrides", chatOverrides: "Chat overrides", inherit: "Inherit", enabled: "Enabled", disabled: "Disabled", muted: "Muted", muteOneHour: "For 1 hour", reset: "Reset",
    mentions: "Mentions", noMentions: "Nobody has mentioned you yet", loadMore: "Load more",
    groupManagement: "Group management", groupName: "Group name", members: "Members", addMember: "Add member", owner: "Owner", administrator: "Administrator", moderator: "Moderator", member: "Member", makeAdmin: "Make administrator", removeAdmin: "Remove administrator", removeMember: "Remove from group", transferOwnership: "Transfer ownership", leaveGroup: "Leave group", groupPhoto: "Group photo", selectUsers: "Select members", createGroup: "Create group", next: "Next", selectedCount: "Selected: {count}", directChat: "Direct chat",
    serverManagement: "Server settings", overview: "Overview", categories: "Categories", channels: "Channels", roles: "Roles", bans: "Bans", auditLog: "Audit log", permissions: "Permissions", overrides: "Channel permissions", addCategory: "Add category", addChannel: "Add channel", addRole: "Add role", textChannel: "Text channel", voiceChannel: "Voice channel", edit: "Edit", delete: "Delete", kick: "Kick", ban: "Ban", unban: "Unban", transferServer: "Transfer server", leaveServer: "Leave server", deleteServer: "Delete server", serverIcon: "Server icon", permissionAllow: "Allow", permissionDeny: "Deny", permissionInherit: "Inherit", defaultMembers: "All members", noItems: "Nothing here yet",
    save: "Save", cancel: "Cancel", close: "Close", search: "Search", add: "Add", confirm: "Confirm", operationFailed: "Action failed", saved: "Saved", loading: "Loading…", reason: "Reason", name: "Name", userNotFound: "User not found", quietHoursStart: "Starts", quietHoursEnd: "Ends", chooseTime: "Choose time", openSource: "Open source", sourceCode: "Source code", legalNotice: "Snezhok is free software under GNU GPL version 3 or later. It comes without any warranty. Corresponding source and third-party notices are available in the public repository.",
  },
} as const;

export type ProductCopyKey = keyof typeof copy.en;
export function productCopy(language: "ru" | "en", key: ProductCopyKey, values?: Record<string, string | number>) {
  const template: string = copy[language][key];
  return values ? Object.entries(values).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)), template) : template;
}
