plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'xyz.merchedits.snezhok'
version = '1.0.0'

android {
  namespace "xyz.merchedits.snezhok.transfer"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation "androidx.work:work-runtime-ktx:2.11.2"
  testImplementation "junit:junit:4.13.2"
}
