import { StyleSheet } from "react-native";

export const messageBubbleStyles = StyleSheet.create({
  selectionFrame: { width: "100%", position: "relative" },
  selectionContent: { width: "100%" },
  selectionMarker: { position: "absolute", left: 8, top: "50%", marginTop: -11, zIndex: 2 },
  selectionCircle: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: "center", justifyContent: "center" },
  row: { width: "100%", paddingHorizontal: 8, marginVertical: 2 },
  mineRow: { alignItems: "flex-end" },
  theirRow: { alignItems: "flex-start" },
  bubble: { maxWidth: "82%", minWidth: 78, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8 },
  mediaBubble: { maxWidth: "86%", minWidth: 0, overflow: "hidden" },
  mineBubble: { borderTopRightRadius: 8 },
  theirBubble: { borderTopLeftRadius: 8 },
  activityBubble: { maxWidth: "94%", width: 302, borderWidth: 0 },
  channelRow: { width: "100%", flexDirection: "row", paddingHorizontal: 12, paddingVertical: 3 },
  channelAvatar: { width: 40, marginRight: 10 },
  channelContent: { flex: 1, minWidth: 0, paddingRight: 8, borderRadius: 10 },
  authorLine: { flexDirection: "row", alignItems: "baseline", gap: 7, marginBottom: 2 },
  channelAuthor: { fontSize: 15, fontWeight: "700" },
  channelTime: { fontSize: 11 },
  channelFooter: { justifyContent: "flex-start" },
  sender: { fontSize: 13, fontWeight: "700", marginBottom: 3 },
  text: { fontSize: 16, lineHeight: 21 },
  inlineTextWrap: { flexDirection: "row", alignItems: "flex-end" },
  inlineMessageText: { flexShrink: 1 },
  inlineMeta: { flexShrink: 0, marginLeft: 7, marginBottom: 1 },
  voiceContentRoot: { position: "relative" },
  voiceMetaOverlay: { position: "absolute", right: 0, bottom: 0 },
  reply: { borderLeftWidth: 3, paddingLeft: 7, marginBottom: 6 },
  replyName: { fontSize: 12, fontWeight: "700" },
  replyText: { fontSize: 12, marginTop: 1 },
  forwarded: { flexDirection: "row", alignItems: "center", gap: 4, marginBottom: 5 },
  forwardedText: { fontSize: 12, fontWeight: "700" },
  footer: { minHeight: 20, flexDirection: "row", alignItems: "flex-end", marginTop: 3, gap: 5 },
  footerSpacer: { flex: 1, minWidth: 5 },
  meta: { flexDirection: "row", alignItems: "center", gap: 3 },
  overlayIsland: { minHeight: 22, paddingHorizontal: 6, borderRadius: 11, backgroundColor: "rgba(17,18,24,0.58)" },
  pinned: { flexDirection: "row", alignItems: "center", gap: 2 },
  time: { fontSize: 10 },
  edited: { fontSize: 10 },
  mediaStage: { position: "relative" },
  mediaSenderOverlay: { position: "absolute", left: 6, top: 6, maxWidth: "72%" },
  mediaSender: { color: "white", fontSize: 12, fontWeight: "800" },
  mediaReactionOverlay: { position: "absolute", left: 6, bottom: 6, maxWidth: "62%" },
  mediaMetaOverlay: { position: "absolute", right: 6, bottom: 6 },
  photo: { borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "#202329" },
  album: { width: 286, gap: 2, borderRadius: 16, overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: "rgba(255,255,255,0.18)" },
  albumRow: { flexDirection: "row", gap: 2 },
  albumTile: { flex: 1, minWidth: 0, overflow: "hidden", backgroundColor: "#202329" },
  albumPlay: { position: "absolute", left: "50%", top: "50%", width: 36, height: 36, marginLeft: -18, marginTop: -18, borderRadius: 18, backgroundColor: "rgba(0,0,0,0.55)", alignItems: "center", justifyContent: "center" },
  albumDuration: { position: "absolute", right: 5, top: 5, minWidth: 30, height: 18, paddingHorizontal: 5, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.62)" },
  video: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  videoPreview: { borderRadius: 16, overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "#202329" },
  videoPlaceholder: { backgroundColor: "#202329" },
  videoPlay: { position: "absolute", left: "50%", top: "50%", width: 44, height: 44, marginLeft: -22, marginTop: -22, borderRadius: 22, backgroundColor: "rgba(0,0,0,0.55)", alignItems: "center", justifyContent: "center" },
  videoDurationBadge: { position: "absolute", right: 7, top: 7, minWidth: 34, height: 20, paddingHorizontal: 6, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.62)" },
  videoDurationText: { color: "white", fontSize: 11, fontWeight: "600", fontVariant: ["tabular-nums"] },
  file: { width: 250, minHeight: 58, borderRadius: 11, padding: 8, flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 4 },
  fileIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  fileText: { flex: 1 },
  filename: { fontSize: 13, fontWeight: "600" },
  filesize: { fontSize: 11, marginTop: 3 },
  reactions: { flexDirection: "row", flexWrap: "wrap", gap: 4, flexShrink: 1 },
  reaction: { borderWidth: 1, borderRadius: 12, minWidth: 27, height: 24, paddingHorizontal: 6, alignItems: "center", justifyContent: "center" },
  overlayReaction: { backgroundColor: "rgba(17,18,24,0.58)", borderColor: "rgba(255,255,255,0.22)" },
  emoji: { fontSize: 13 },
  failedAttachment: { width: 238, minHeight: 48, borderRadius: 11, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  failedAttachmentCompact: { flex: 1, minWidth: 0, height: "100%", alignItems: "center", justifyContent: "center" },
  failedAttachmentText: { flexShrink: 1, fontSize: 12, fontWeight: "700" },
});
