import { StyleSheet } from "react-native";

export const iconActionStyle = {
  width: 40,
  height: 40,
  borderRadius: 20,
  alignItems: "center",
  justifyContent: "center",
} as const;
export const attemptStyle = {
  minHeight: 28,
  flexDirection: "row",
  alignItems: "center",
  gap: 6,
} as const;

export const cooperativeActivityStyles = StyleSheet.create({
  confetti: {
    position: "absolute",
    left: "50%",
    top: "34%",
    width: 1,
    height: 1,
    zIndex: 20,
  },
  confettiPiece: {
    position: "absolute",
    width: 8,
    height: 13,
    borderRadius: 3,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  headerInstruction: { fontSize: 21, lineHeight: 27, fontWeight: "800", marginTop: 8 },
  colorAssignment: {
    minHeight: 58,
    borderRadius: 16,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 10,
  },
  colorDot: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.7)",
  },
  collageLoading: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  avatarStack: { flexDirection: "row", alignItems: "center", minWidth: 27 },
  root: { flex: 1, justifyContent: "flex-end" },
  sheet: {
    maxHeight: "92%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 18,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 18,
    gap: 12,
  },
  eyebrow: { fontSize: 12, fontWeight: "800", marginBottom: 5 },
  title: { fontSize: 18, lineHeight: 23, fontWeight: "800", maxWidth: 300 },
  standaloneTitle: { fontSize: 22, lineHeight: 27 },
  close: {
    marginLeft: "auto",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  content: { padding: 18, paddingBottom: 10 },
  largeInput: {
    minHeight: 124,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    fontSize: 16,
    lineHeight: 22,
    textAlignVertical: "top",
  },
  input: {
    height: 50,
    borderRadius: 15,
    paddingHorizontal: 14,
    fontSize: 15,
    marginTop: 10,
  },
  primary: {
    height: 50,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  actionText: { color: "#FFF", fontSize: 15, fontWeight: "800" },
  error: { fontSize: 13, lineHeight: 18, marginTop: 10 },
  quietActions: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
  },
  quietText: { fontSize: 13, fontWeight: "700" },
  terminalAction: { minHeight: 44, paddingHorizontal: 18, alignItems: "center", justifyContent: "center" },
  blitzRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 8,
  },
  choice: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  or: { fontSize: 18 },
  explainer: { fontSize: 14, lineHeight: 20 },
  addLine: { flexDirection: "row", gap: 8, marginBottom: 12 },
  inlineInput: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    paddingHorizontal: 13,
    fontSize: 15,
  },
  plus: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  listItem: {
    minHeight: 60,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 10,
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  flex: { flex: 1 },
  itemTitle: { fontSize: 15, lineHeight: 20, fontWeight: "700" },
  itemMeta: { fontSize: 12, marginTop: 3 },
  ratings: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    paddingTop: 7,
  },
  rating: {
    width: 35,
    height: 35,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  picked: { borderRadius: 18, padding: 14, marginBottom: 10 },
  pickedTitle: { fontSize: 19, fontWeight: "800", marginTop: 5 },
  pickActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  canvas: {
    width: "100%",
    aspectRatio: 1.25,
    backgroundColor: "#FFFDF8",
    borderRadius: 18,
    overflow: "hidden",
    marginTop: 12,
  },
  liveLabel: {
    marginTop: 10,
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
  },
  collageGrid: {
    width: "100%",
    aspectRatio: 1,
    overflow: "hidden",
    borderRadius: 20,
    marginTop: 12,
  },
  collageCell: {
    position: "absolute",
    width: "34.2%",
    height: "34.2%",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  collageMedia: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  collageProgress: {
    position: "absolute",
    width: 48,
    minHeight: 36,
    borderRadius: 18,
    paddingHorizontal: 7,
    backgroundColor: "rgba(18,18,24,0.66)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  collageProgressText: { color: "#FFFFFF", fontSize: 10, fontWeight: "800" },
  collagePhoto: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 20,
    marginTop: 12,
  },
  collageResult: { marginBottom: 18 },
  twoActions: { flexDirection: "row", gap: 8, marginTop: 12 },
  secondaryButton: {
    flex: 1,
    height: 48,
    borderRadius: 15,
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  primarySmall: {
    flex: 1,
    height: 48,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  waiting: { borderRadius: 18, padding: 18, alignItems: "center", gap: 10 },
  resultTitle: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "800",
    marginBottom: 12,
  },
  resultEntry: { borderRadius: 16, padding: 13, marginBottom: 7 },
  resultMedia: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 10,
  },
  resultPhoto: { width: "48%", aspectRatio: 1, borderRadius: 15 },
  memorySong: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  songResult: {
    minHeight: 64,
    borderRadius: 17,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 7,
  },
  songPlay: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  guessLine: { fontSize: 15, fontWeight: "700", marginTop: 7 },
  blitzResult: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginBottom: 6,
  },
});
