apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'xyz.merchedits.snezhok.core'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
