import type { AppSettings } from "@snezhok/contracts";

export const defaultSettings: AppSettings = {
  theme: "system",
  accent: "blue",
  fontScale: 1,
  density: "comfortable",
  bubbleRadius: 16,
  reducedMotion: false,
  highContrast: false,
  language: "ru",
  readReceipts: true,
  showLastSeen: true,
  stripMediaLocation: true,
  defaultUploadQuality: "auto",
  autoDownloadWifi: true,
  autoDownloadMobile: false,
  noiseSuppression: "standard",
  echoCancellation: true,
  autoGainControl: true,
  microphoneMode: "phone",
  callAudioRoute: "auto",
  callQuality: "auto",
  screenShareQuality: "auto",
  pushToTalk: false,
  messageNotifications: true,
  callNotifications: true,
  notificationPreviews: true,
  notificationSound: true,
  notificationMobile: true,
  notificationMentionsOnly: false,
  quietHoursStart: null,
  quietHoursEnd: null,
  quietHoursTimezoneOffsetMinutes: 0,
};
