import type { ChoicePrompt, LocalizedText } from "./types.js";

export const blitzPrompts: ChoicePrompt[] = [
  choice("cats-dogs", "Кошки", "Cats", "Собаки", "Dogs"),
  choice("sunrise-sunset", "Рассвет", "Sunrise", "Закат", "Sunset"),
  choice("sweet-salty", "Сладкое", "Sweet", "Солёное", "Salty"),
  choice("home-out", "Остаться дома", "Stay home", "Куда-нибудь пойти", "Go out"),
  choice("voice-text", "Голосовые", "Voice messages", "Текст", "Text"),
  choice("plan-spontaneous", "План", "A plan", "Спонтанность", "Spontaneity"),
  choice("mountains-sea", "Горы", "Mountains", "Море", "Sea"),
  choice("movie-series", "Фильм", "Movie", "Сериал", "Series"),
  choice("early-late", "Рано вставать", "Early bird", "Поздно ложиться", "Night owl"),
  choice("cook-order", "Готовить", "Cook", "Заказывать", "Order in"),
  choice("photo-video", "Фото", "Photo", "Видео", "Video"),
  choice("city-nature", "Город", "City", "Природа", "Nature"),
  choice("tea-coffee", "Чай", "Tea", "Кофе", "Coffee"),
  choice("book-podcast", "Книга", "Book", "Подкаст", "Podcast"),
  choice("summer-winter", "Лето", "Summer", "Зима", "Winter"),
  choice("rain-snow", "Дождь", "Rain", "Снег", "Snow"),
  choice("window-aisle", "У окна", "Window seat", "У прохода", "Aisle seat"),
  choice("breakfast-dinner", "Большой завтрак", "Big breakfast", "Большой ужин", "Big dinner"),
  choice("call-walk", "Позвонить", "Call", "Встретиться на прогулке", "Meet for a walk"),
  choice("museum-concert", "Музей", "Museum", "Концерт", "Concert"),
  choice("train-plane", "Поезд", "Train", "Самолёт", "Plane"),
  choice("paper-digital", "Бумага", "Paper", "Цифра", "Digital"),
  choice("board-video-game", "Настольная игра", "Board game", "Видеоигра", "Video game"),
  choice("quiet-party", "Тихий вечер", "Quiet evening", "Шумная вечеринка", "Loud party"),
  choice("cake-icecream", "Торт", "Cake", "Мороженое", "Ice cream"),
  choice("message-meme", "Длинное сообщение", "Long message", "Идеальный мем", "Perfect meme"),
  choice("beach-forest", "Пляж", "Beach", "Лес", "Forest"),
  choice("hotel-cabin", "Отель", "Hotel", "Домик", "Cabin"),
  choice("routine-surprise", "Знакомый ритуал", "Familiar ritual", "Сюрприз", "Surprise"),
  choice("pancakes-eggs", "Блины", "Pancakes", "Яичница", "Eggs"),
  choice("sneakers-boots", "Кроссовки", "Sneakers", "Ботинки", "Boots"),
  choice("sun-clouds", "Солнце", "Sun", "Облака", "Clouds"),
  choice("sing-dance", "Петь", "Sing", "Танцевать", "Dance"),
  choice("learn-make", "Узнать новое", "Learn something", "Сделать руками", "Make something"),
  choice("minimal-cozy", "Минимализм", "Minimal", "Много уюта", "Extra cosy"),
  choice("gift-experience", "Подарок", "Gift", "Впечатление", "Experience"),
  choice("morning-night-shower", "Душ утром", "Morning shower", "Душ вечером", "Evening shower"),
  choice("map-wander", "С картой", "Use a map", "Просто гулять", "Just wander"),
  choice("savory-breakfast", "Сытный завтрак", "Savory breakfast", "Сладкий завтрак", "Sweet breakfast"),
  choice("old-new-music", "Старая любимая музыка", "Old favourites", "Новые треки", "New music"),
  choice("talk-listen", "Много говорить", "Talk a lot", "Больше слушать", "Listen more"),
  choice("one-long-many-short", "Одна длинная поездка", "One long trip", "Много коротких", "Many short trips"),
  choice("sunset-stars", "Смотреть закат", "Watch sunset", "Смотреть на звёзды", "Watch stars"),
  choice("flowers-snacks", "Цветы", "Flowers", "Любимые снеки", "Favourite snacks"),
  choice("documentary-comedy", "Документалка", "Documentary", "Комедия", "Comedy"),
  choice("bath-shower", "Ванна", "Bath", "Душ", "Shower"),
  choice("open-window-blanket", "Открытое окно", "Open window", "Тёплый плед", "Warm blanket"),
  choice("cards-puzzle", "Карты", "Cards", "Пазл", "Puzzle"),
  choice("market-mall", "Рынок", "Market", "Торговый центр", "Mall"),
  choice("reuse-new", "Починить старое", "Fix the old one", "Купить новое", "Buy a new one"),
  choice("talk-now-think", "Обсудить сразу", "Talk now", "Сначала подумать", "Think first"),
  choice("shared-separate-dessert", "Один десерт на двоих", "Share dessert", "Каждому свой", "One each"),
  choice("big-small-company", "Большая компания", "Big group", "Два-три человека", "Two or three people"),
  choice("farm-space", "Жить на ферме", "Live on a farm", "Жить на станции в космосе", "Live in space"),
  choice("repeat-improvise", "Любимый проверенный рецепт", "Trusted recipe", "Импровизация", "Improvise"),
  choice("hot-cold-drink", "Горячий напиток", "Hot drink", "Холодный напиток", "Cold drink"),
  choice("photos-memories", "Снять много фото", "Take many photos", "Почти не снимать", "Hardly take any"),
  choice("centre-suburb", "В центре", "City centre", "На окраине", "Outskirts"),
  choice("slow-fast-morning", "Медленное утро", "Slow morning", "Быстро начать день", "Start fast"),
  choice("decorate-plain", "Украшать к празднику", "Decorate", "Оставить всё спокойно", "Keep it simple"),
  choice("ask-guess", "Спросить прямо", "Ask directly", "Попробовать угадать", "Try to guess"),
  choice("souvenir-photo", "Привезти сувенир", "Bring a souvenir", "Оставить только фото", "Keep only photos"),
  choice("laugh-cry-movie", "Смеяться над фильмом", "Laugh at a movie", "Поплакать над фильмом", "Cry at a movie"),
  choice("warm-cool-light", "Тёплый свет", "Warm light", "Холодный свет", "Cool light"),
  choice("long-short-walk", "Долгая прогулка", "Long walk", "Короткая поездка", "Short drive"),
  choice("notes-memory", "Записать", "Write it down", "Положиться на память", "Trust memory"),
  choice("share-keep-news", "Сразу поделиться новостью", "Share news instantly", "Немного подержать при себе", "Keep it briefly"),
  choice("fruit-chocolate", "Фрукты", "Fruit", "Шоколад", "Chocolate"),
  choice("terrace-fireplace", "Терраса", "Terrace", "Камин", "Fireplace"),
  choice("weekday-weekend-date", "Встреча среди недели", "Weekday date", "Встреча в выходной", "Weekend date"),
  choice("same-new-place", "Любимое место", "Favourite place", "Новое место", "New place"),
  choice("pack-light-ready", "Собраться налегке", "Pack light", "Взять всё нужное", "Be fully prepared"),
];

export const tinyQuests: LocalizedText[] = [
  { ru: "Сфотографируй предмет вокруг любимого цвета", en: "Photograph something nearby in your favourite colour" },
  { ru: "Покажи самый странный предмет рядом", en: "Show the weirdest object near you" },
  { ru: "Покажи, что ты сейчас пьёшь", en: "Show what you are drinking right now" },
  { ru: "Найди вещь, которая напоминает о детстве", en: "Find something that reminds you of childhood" },
  { ru: "Сфотографируй самый уютный угол рядом", en: "Photograph the cosiest corner near you" },
  { ru: "Поймай в кадр красивую тень", en: "Capture a beautiful shadow" },
  { ru: "Найди предмет с приятной текстурой", en: "Find an object with a satisfying texture" },
  { ru: "Покажи вещь, которой пользуешься каждый день", en: "Show something you use every day" },
  { ru: "Сфотографируй что-нибудь совсем крошечное", en: "Photograph something really tiny" },
  { ru: "Найди вокруг идеальный круг", en: "Find a perfect circle nearby" },
  { ru: "Покажи вид из ближайшего окна", en: "Show the view from the nearest window" },
  { ru: "Сфотографируй то, что сегодня тебя порадовало", en: "Photograph something that made you happy today" },
  { ru: "Найди предмет старше тебя", en: "Find an object older than you" },
  { ru: "Покажи самый яркий цвет рядом", en: "Show the brightest colour near you" },
  { ru: "Сними то, что прямо сейчас звучит", en: "Photograph whatever is making a sound right now" },
  { ru: "Найди вещь с забавным лицом", en: "Find an object that looks like it has a funny face" },
  { ru: "Покажи свою сегодняшнюю обувь", en: "Show the shoes you are wearing today" },
  { ru: "Сфотографируй что-нибудь мягкое", en: "Photograph something soft" },
  { ru: "Найди предмет, который хочется подарить другому", en: "Find something you would like to give someone" },
  { ru: "Покажи самый беспорядочный угол в пределах видимости", en: "Show the messiest spot you can see" },
  { ru: "Сфотографируй красивое отражение", en: "Photograph a beautiful reflection" },
  { ru: "Найди вещь, которую давно пора починить", en: "Find something you have been meaning to fix" },
  { ru: "Покажи ингредиент для идеального перекуса", en: "Show an ingredient for the perfect snack" },
  { ru: "Сними что-нибудь с интересным узором", en: "Capture something with an interesting pattern" },
  { ru: "Найди вещь, связанную с твоим хобби", en: "Find something connected to your hobby" },
  { ru: "Покажи предмет, без которого не выходишь из дома", en: "Show something you never leave home without" },
  { ru: "Сфотографируй самый спокойный цвет вокруг", en: "Photograph the calmest colour around you" },
  { ru: "Найди смешную надпись", en: "Find a funny bit of text" },
  { ru: "Покажи то, что лежит у тебя слева", en: "Show what is immediately to your left" },
  { ru: "Сфотографируй любимую кружку или стакан", en: "Photograph your favourite mug or glass" },
  { ru: "Найди предмет необычной формы", en: "Find an unusually shaped object" },
  { ru: "Покажи, что сейчас у тебя в кармане или сумке", en: "Show something currently in your pocket or bag" },
  { ru: "Сфотографируй то, что пахнет приятно", en: "Photograph something that smells good" },
  { ru: "Найди вещь, которую ты сделал(а) сам(а)", en: "Find something you made yourself" },
  { ru: "Покажи маленький признак текущего сезона", en: "Show a small sign of the current season" },
  { ru: "Сфотографируй любимое место для сидения", en: "Photograph your favourite place to sit" },
  { ru: "Найди вещь, которую никогда не выбросишь", en: "Find something you would never throw away" },
  { ru: "Покажи самое зелёное, что видишь", en: "Show the greenest thing you can see" },
  { ru: "Сними предмет с историей", en: "Photograph an object with a story" },
  { ru: "Найди неожиданно красивую бытовую деталь", en: "Find an unexpectedly beautiful everyday detail" },
  { ru: "Покажи последнее, что ты купил(а)", en: "Show the last thing you bought" },
  { ru: "Сфотографируй что-нибудь прозрачное", en: "Photograph something transparent" },
  { ru: "Найди вещь, которая всегда теряется", en: "Find something that always gets lost" },
  { ru: "Покажи свой текущий источник света", en: "Show your current source of light" },
  { ru: "Сфотографируй предмет, который приятно держать в руках", en: "Photograph something pleasant to hold" },
  { ru: "Найди рядом число", en: "Find a number nearby" },
  { ru: "Покажи кусочек своего рабочего места", en: "Show a corner of your workspace" },
  { ru: "Сними самую прямую линию вокруг", en: "Capture the straightest line around you" },
  { ru: "Найди вещь, которая напоминает о путешествии", en: "Find something that reminds you of a trip" },
  { ru: "Покажи предмет, который обычно никто не замечает", en: "Show an object people usually overlook" },
  { ru: "Сфотографируй красивое сочетание двух цветов", en: "Photograph a beautiful pair of colours" },
  { ru: "Найди самую удобную вещь рядом", en: "Find the most comfortable thing nearby" },
  { ru: "Покажи что-нибудь, что можно сложить", en: "Show something that can be folded" },
  { ru: "Сними предмет, который пережил много лет", en: "Photograph an object that has lasted many years" },
  { ru: "Найди что-нибудь неожиданно блестящее", en: "Find something unexpectedly shiny" },
  { ru: "Покажи свой самый полезный маленький предмет", en: "Show your most useful small object" },
  { ru: "Сфотографируй то, к чему хочется прикоснуться", en: "Photograph something you want to touch" },
  { ru: "Найди вещь, которая выглядит как произведение искусства", en: "Find something that looks like a work of art" },
  { ru: "Покажи свою любимую книгу поблизости", en: "Show your favourite book nearby" },
  { ru: "Сними то, что напоминает о другом человеке", en: "Photograph something that reminds you of someone" },
  { ru: "Найди предмет, который мог бы быть талисманом", en: "Find an object that could be a lucky charm" },
  { ru: "Покажи самую тёплую вещь рядом", en: "Show the warmest thing nearby" },
  { ru: "Сфотографируй случайную композицию из трёх предметов", en: "Photograph a random composition of three objects" },
  { ru: "Найди вокруг маленькое несовершенство", en: "Find a tiny imperfection nearby" },
  { ru: "Покажи то, что хотел(а) бы съесть прямо сейчас", en: "Show something you would like to eat right now" },
  { ru: "Сними предмет с любимой буквой", en: "Photograph something featuring your favourite letter" },
  { ru: "Найди вещь, которая делает день проще", en: "Find something that makes your day easier" },
  { ru: "Покажи самый тихий угол вокруг", en: "Show the quietest corner around you" },
  { ru: "Сфотографируй что-нибудь симметричное", en: "Photograph something symmetrical" },
  { ru: "Найди предмет, который подходит твоему настроению", en: "Find an object that matches your mood" },
  { ru: "Покажи красивую случайность рядом", en: "Show a beautiful accident nearby" },
  { ru: "Сними то, что ты возьмёшь с собой завтра", en: "Photograph something you will take with you tomorrow" },
  { ru: "Найди маленькую деталь любимого цвета другого человека", en: "Find a small detail in the other person's favourite colour" },
  { ru: "Покажи вещь, за которую ты сегодня благодарен(-на)", en: "Show something you are grateful for today" },
  { ru: "Сфотографируй свой сегодняшний маленький уют", en: "Photograph today's little piece of comfort" },
];

export const songPrompts: LocalizedText[] = [
  { ru: "Песня, которая вызывает ностальгию", en: "A song that makes you nostalgic" },
  { ru: "Песня, которую ты включил(а) бы в два часа ночи", en: "A song you would play at 2 AM" },
  { ru: "Песня для совместной поездки", en: "A song for a road trip together" },
  { ru: "Песня, которую хочется услышать впервые снова", en: "A song you wish you could hear for the first time again" },
  { ru: "Песня для медленного воскресного утра", en: "A song for a slow Sunday morning" },
  { ru: "Песня, которая всегда улучшает настроение", en: "A song that always improves your mood" },
  { ru: "Песня из твоего самого яркого лета", en: "A song from your most vivid summer" },
  { ru: "Песня для прогулки под дождём", en: "A song for walking in the rain" },
  { ru: "Песня, которую ты знаешь почти наизусть", en: "A song you almost know by heart" },
  { ru: "Песня, которая звучит как дом", en: "A song that sounds like home" },
  { ru: "Песня для финальных титров сегодняшнего дня", en: "A song for today's end credits" },
  { ru: "Песня, которую недооценивают", en: "An underrated song" },
  { ru: "Песня для первого снега", en: "A song for the first snow" },
  { ru: "Песня, которую хочется слушать в наушниках", en: "A song that deserves headphones" },
  { ru: "Песня, напоминающая о важном человеке", en: "A song that reminds you of someone important" },
  { ru: "Песня для пустого ночного города", en: "A song for an empty city at night" },
  { ru: "Песня, которую ты недавно открыл(а)", en: "A song you discovered recently" },
  { ru: "Песня из любимого фильма или сериала", en: "A song from a favourite film or series" },
  { ru: "Песня, которая помогает собраться", en: "A song that helps you pull yourself together" },
  { ru: "Песня для готовки вдвоём", en: "A song for cooking together" },
  { ru: "Песня, под которую невозможно не двигаться", en: "A song you cannot stay still to" },
  { ru: "Песня, которая звучит как влюблённость", en: "A song that sounds like falling in love" },
  { ru: "Песня для долгой дороги на поезде", en: "A song for a long train ride" },
  { ru: "Песня, которую тебе показали и ты сохранил(а)", en: "A song someone showed you that you kept" },
  { ru: "Песня для тихого вечера без планов", en: "A song for a quiet evening with no plans" },
  { ru: "Песня, которая даёт уверенность", en: "A song that gives you confidence" },
  { ru: "Песня, с которой начался бы твой концерт", en: "A song that would open your concert" },
  { ru: "Песня, которой ты закончил(а) бы концерт", en: "A song that would close your concert" },
  { ru: "Песня, подходящая сегодняшней погоде", en: "A song that matches today's weather" },
  { ru: "Песня, которую приятно слушать в машине", en: "A song that feels great in the car" },
  { ru: "Песня из детства, которую помнишь до сих пор", en: "A childhood song you still remember" },
  { ru: "Песня, которую ты включаешь слишком громко", en: "A song you play too loudly" },
  { ru: "Песня для неожиданно хорошего дня", en: "A song for an unexpectedly good day" },
  { ru: "Песня, которая помогает уснуть", en: "A song that helps you fall asleep" },
  { ru: "Песня для танца на кухне", en: "A song for dancing in the kitchen" },
  { ru: "Песня с особенно красивым текстом", en: "A song with especially beautiful lyrics" },
  { ru: "Песня с любимым вступлением", en: "A song with your favourite opening" },
  { ru: "Песня, которая напоминает о море", en: "A song that reminds you of the sea" },
  { ru: "Песня для смелого нового начала", en: "A song for a brave new beginning" },
  { ru: "Песня, которую хочется отправить без объяснений", en: "A song you would send without explanation" },
  { ru: "Песня для уютного зимнего вечера", en: "A song for a cosy winter evening" },
  { ru: "Песня, которая звучит как свобода", en: "A song that sounds like freedom" },
  { ru: "Песня, которую ты любишь вопреки всему", en: "A song you love against your better judgement" },
  { ru: "Песня для совместного маленького праздника", en: "A song for a little celebration together" },
  { ru: "Песня, которая возвращает энергию", en: "A song that brings your energy back" },
  { ru: "Песня, которая звучала бы в фильме о нас", en: "A song that would play in a film about us" },
  { ru: "Песня для момента, который хочется запомнить", en: "A song for a moment worth remembering" },
  { ru: "Песня, которую стоит послушать прямо сейчас", en: "A song worth hearing right now" },
];

export const drawWords: LocalizedText[] = [
  word("снеговик", "snowman"), word("чайник", "kettle"), word("жираф", "giraffe"), word("космонавт", "astronaut"),
  word("пингвин", "penguin"), word("торт", "cake"), word("велосипед", "bicycle"), word("облако", "cloud"),
  word("улитка", "snail"), word("маяк", "lighthouse"), word("кактус", "cactus"), word("ракета", "rocket"),
  word("зонт", "umbrella"), word("робот", "robot"), word("динозавр", "dinosaur"), word("замок", "castle"),
  word("гитара", "guitar"), word("арбуз", "watermelon"), word("осьминог", "octopus"), word("корона", "crown"),
  word("вертолёт", "helicopter"), word("пицца", "pizza"), word("пальма", "palm tree"), word("корабль", "ship"),
  word("лампа", "lamp"), word("бабочка", "butterfly"), word("подушка", "pillow"), word("мороженое", "ice cream"),
  word("чемодан", "suitcase"), word("черепаха", "turtle"), word("телескоп", "telescope"), word("будильник", "alarm clock"),
  word("подарок", "present"), word("мост", "bridge"), word("медуза", "jellyfish"), word("самолёт", "aeroplane"),
  word("кресло", "armchair"), word("павлин", "peacock"), word("фонтан", "fountain"), word("рюкзак", "backpack"),
  word("микрофон", "microphone"), word("вулкан", "volcano"), word("свеча", "candle"), word("кенгуру", "kangaroo"),
  word("наушники", "headphones"), word("поезд", "train"), word("цветок", "flower"), word("крокодил", "crocodile"),
  word("скейтборд", "skateboard"), word("гамбургер", "hamburger"), word("воздушный шар", "balloon"), word("лошадь", "horse"),
  word("пылесос", "vacuum cleaner"), word("водопад", "waterfall"), word("кровать", "bed"), word("енот", "raccoon"),
  word("конверт", "envelope"), word("подводная лодка", "submarine"), word("печенье", "cookie"), word("дерево", "tree"),
  word("фотоаппарат", "camera"), word("кит", "whale"), word("солнце", "sun"), word("барабан", "drum"),
  word("паутина", "spider web"), word("книга", "book"), word("попугай", "parrot"), word("костёр", "campfire"),
  word("ботинок", "boot"), word("дельфин", "dolphin"), word("ключ", "key"), word("гриб", "mushroom"),
  word("снегирь", "bullfinch"), word("самокат", "scooter"), word("часы", "clock"), word("тигр", "tiger"),
  word("лестница", "ladder"), word("ананас", "pineapple"), word("дом", "house"), word("краб", "crab"),
  word("шляпа", "hat"), word("луна", "moon"), word("очки", "glasses"), word("рыцарь", "knight"),
  word("парусник", "sailboat"), word("ложка", "spoon"), word("замочная скважина", "keyhole"), word("лев", "lion"),
  word("радуга", "rainbow"), word("корзина", "basket"), word("пчела", "bee"), word("диван", "sofa"),
  word("компас", "compass"), word("кролик", "rabbit"), word("пончики", "doughnuts"), word("привидение", "ghost"),
  word("карусель", "carousel"), word("морская звезда", "starfish"), word("клевер", "clover"), word("ферма", "farm"),
  word("фонарик", "torch"), word("белка", "squirrel"), word("небоскрёб", "skyscraper"), word("варежка", "mitten"),
];

function choice(id: string, leftRu: string, leftEn: string, rightRu: string, rightEn: string): ChoicePrompt {
  return { id, left: { ru: leftRu, en: leftEn }, right: { ru: rightRu, en: rightEn } };
}

function word(ru: string, en: string): LocalizedText {
  return { ru, en };
}
