import type { LocalizedText } from "./types.js";

export const questionCatalog: Record<string, LocalizedText[]> = {
  silly: [
    { ru: "Какой бесполезный талант ты хотел(а) бы получить?", en: "Which useless talent would you love to have?" },
    { ru: "Если бы наш чат был животным, каким?", en: "If our chat were an animal, which one would it be?" },
    { ru: "Какую еду ты смог(ла) бы есть неделю подряд?", en: "Which food could you eat for a week straight?" },
    { ru: "Какое самое нелепое имя подошло бы домашнему дракону?", en: "What ridiculous name would suit a pet dragon?" },
    { ru: "Какой звук должен сопровождать твоё эффектное появление?", en: "Which sound should play whenever you make a dramatic entrance?" },
    { ru: "Какой предмет дома тайно замышляет переворот?", en: "Which object at home is secretly plotting a takeover?" },
    { ru: "Если бы носки умели разговаривать, на что бы они жаловались?", en: "If socks could talk, what would they complain about?" },
    { ru: "Какой странный закон ты бы ввёл(а) на один день?", en: "Which strange law would you introduce for one day?" },
    { ru: "Какое блюдо лучше всего описывает твоё настроение сегодня?", en: "Which dish best describes your mood today?" },
    { ru: "Какой злодей получился бы из тебя в очень добром мультфильме?", en: "What kind of villain would you be in a very wholesome cartoon?" },
    { ru: "Какой обычный предмет ты бы выбрал(а) своим талисманом?", en: "Which ordinary object would you choose as your mascot?" },
    { ru: "Если бы смех был валютой, на что бы ты уже накопил(а)?", en: "If laughter were currency, what could you already afford?" },
    { ru: "Какую абсурдную олимпийскую дисциплину ты бы выиграл(а)?", en: "Which absurd Olympic event would you win?" },
    { ru: "Какая песня подошла бы погоне за последним кусочком пиццы?", en: "Which song would fit a chase for the last slice of pizza?" },
    { ru: "Какой запах должен быть у облаков?", en: "What should clouds smell like?" },
    { ru: "Какой эмодзи заслуживает отдельного праздника?", en: "Which emoji deserves its own holiday?" },
    { ru: "Если бы холодильник выдавал советы, что бы он сказал тебе сегодня?", en: "If your fridge gave advice, what would it tell you today?" },
    { ru: "Какой предмет одежды получил бы у тебя главную роль в кино?", en: "Which item of clothing would get the lead role in your movie?" },
    { ru: "Как называлась бы наша очень плохая рок-группа?", en: "What would our very bad rock band be called?" },
    { ru: "Какой суперспособностью особенно неудобно пользоваться в автобусе?", en: "Which superpower would be especially awkward on a bus?" },
    { ru: "Какой десерт мог бы стать хорошим президентом?", en: "Which dessert would make a good president?" },
    { ru: "Если бы твой день был мемом, каким?", en: "If your day were a meme, which one would it be?" },
    { ru: "Какое животное наверняка знает слишком много?", en: "Which animal definitely knows too much?" },
    { ru: "Какой нелепый рекорд мы могли бы поставить вместе?", en: "Which ridiculous record could we set together?" },
    { ru: "Какой бытовой навык заслуживает громких аплодисментов?", en: "Which household skill deserves loud applause?" },
    { ru: "Если бы можно было приручить один звук, какой бы ты выбрал(а)?", en: "If you could tame one sound, which would you choose?" },
    { ru: "Какой фильм стал бы лучше, если добавить туда гуся?", en: "Which movie would improve if a goose were added?" },
    { ru: "Какой у тебя был бы пароль в тайный клуб любителей сна?", en: "What would your password be for a secret sleep-lovers club?" },
    { ru: "Какое официальное название дать состоянию «зашёл в комнату и забыл зачем»?", en: "What official name should we give the feeling of entering a room and forgetting why?" },
    { ru: "Кого из нас первым возьмут в команду по выживанию среди зомби и почему?", en: "Which of us gets picked first for a zombie survival team, and why?" },
  ],
  childhood: [
    { ru: "Какая мелочь мгновенно возвращает тебя в детство?", en: "What tiny thing instantly takes you back to childhood?" },
    { ru: "О какой детской мечте ты всё ещё иногда думаешь?", en: "Which childhood dream do you still think about?" },
    { ru: "Какая семейная традиция тебе особенно дорога?", en: "Which family tradition means the most to you?" },
    { ru: "Какой мультфильм ты мог(ла) смотреть снова и снова?", en: "Which cartoon could you watch again and again?" },
    { ru: "Какой запах напоминает тебе дом из детства?", en: "Which smell reminds you of your childhood home?" },
    { ru: "Во что ты чаще всего играл(а) во дворе?", en: "What did you play most often outside?" },
    { ru: "Какой школьный день запомнился неожиданно хорошо?", en: "Which school day do you remember being unexpectedly good?" },
    { ru: "Какая игрушка была для тебя почти живой?", en: "Which toy felt almost alive to you?" },
    { ru: "Какое детское лакомство до сих пор радует?", en: "Which childhood treat still makes you happy?" },
    { ru: "Кем ты хотел(а) стать до того, как узнал(а) о настоящих профессиях?", en: "What did you want to be before you knew about real careers?" },
    { ru: "Какой праздник в детстве казался самым волшебным?", en: "Which childhood holiday felt the most magical?" },
    { ru: "Какую фразу взрослых ты часто слышал(а)?", en: "Which phrase did adults say around you all the time?" },
    { ru: "Какое место казалось огромным, а теперь выглядит маленьким?", en: "Which place felt enormous then but seems small now?" },
    { ru: "Что ты собирал(а) или очень хотел(а) собирать?", en: "What did you collect, or really want to collect?" },
    { ru: "Какой навык ты освоил(а) с особой гордостью?", en: "Which skill did you learn with special pride?" },
    { ru: "Какое приключение по дороге домой ты помнишь?", en: "Which adventure on the way home do you remember?" },
    { ru: "Какая детская книга осталась с тобой?", en: "Which childhood book stayed with you?" },
    { ru: "Какой подарок в детстве удивил тебя сильнее всего?", en: "Which childhood gift surprised you the most?" },
    { ru: "Как выглядело твоё любимое укрытие или тайное место?", en: "What did your favourite hideout or secret place look like?" },
    { ru: "Какую еду ты категорически отказывался(-ась) есть?", en: "Which food did you absolutely refuse to eat?" },
    { ru: "Какой смешной страх был у тебя в детстве?", en: "Which funny fear did you have as a child?" },
    { ru: "Кто первым научил тебя чему-то действительно важному?", en: "Who first taught you something genuinely important?" },
    { ru: "Какую песню часто включали рядом с тобой?", en: "Which song was often played around you?" },
    { ru: "Какой обычный день из детства ты бы прожил(а) ещё раз?", en: "Which ordinary childhood day would you live again?" },
    { ru: "Какое правило дома казалось тебе несправедливым?", en: "Which household rule felt unfair to you?" },
    { ru: "Что ты делал(а), когда хотел(а) побыть один/одна?", en: "What did you do when you wanted to be alone?" },
    { ru: "Какой летний момент ты помнишь особенно ярко?", en: "Which summer moment do you remember most vividly?" },
    { ru: "Как выглядел твой идеальный день рождения?", en: "What did your ideal birthday look like?" },
    { ru: "Какую привычку из семьи ты сохранил(а)?", en: "Which family habit have you kept?" },
    { ru: "Какой совет ты бы дал(а) себе маленькому?", en: "What advice would you give your younger self?" },
  ],
  preferences: [
    { ru: "Как выглядит твой идеальный ленивый выходной?", en: "What would your perfect lazy Sunday look like?" },
    { ru: "Какое место ты всегда рад(а) посетить снова?", en: "Which place are you always happy to revisit?" },
    { ru: "Какой маленький подарок тебя бы сейчас порадовал?", en: "Which small gift would make you happy right now?" },
    { ru: "Какой завтрак способен исправить утро?", en: "Which breakfast can rescue a morning?" },
    { ru: "Какую погоду ты выбрал(а) бы на месяц?", en: "Which weather would you choose for a whole month?" },
    { ru: "Что лучше помогает тебе отдыхать: тишина или знакомые звуки?", en: "What helps you rest better: silence or familiar sounds?" },
    { ru: "Какой формат путешествия тебе ближе всего?", en: "Which style of travel suits you best?" },
    { ru: "Какую комнату ты обустроил(а) бы в первую очередь?", en: "Which room would you decorate first?" },
    { ru: "Какая еда всегда уместна поздно вечером?", en: "Which food always feels right late at night?" },
    { ru: "Какой звук тебе особенно приятно слышать?", en: "Which sound do you especially enjoy hearing?" },
    { ru: "Какой способ провести дождливый день лучший?", en: "What is the best way to spend a rainy day?" },
    { ru: "Какой фильм ты посоветуешь почти любому человеку?", en: "Which movie would you recommend to almost anyone?" },
    { ru: "Что ты выберешь для уютного вечера дома?", en: "What would you choose for a cosy evening at home?" },
    { ru: "Какая часть дня обычно твоя любимая?", en: "Which part of the day is usually your favourite?" },
    { ru: "Какой вид транспорта делает дорогу приятнее?", en: "Which kind of transport makes a journey nicer?" },
    { ru: "Какой вкус мороженого ты защищаешь до конца?", en: "Which ice-cream flavour would you defend forever?" },
    { ru: "Какой запах ты хотел(а) бы сохранить во флаконе?", en: "Which smell would you bottle and keep?" },
    { ru: "Какой город тебе хочется исследовать без плана?", en: "Which city would you like to explore without a plan?" },
    { ru: "Какую вещь ты всегда берёшь в поездку?", en: "Which item do you always take on a trip?" },
    { ru: "Какой домашний ритуал делает день лучше?", en: "Which home ritual makes your day better?" },
    { ru: "Какая музыка помогает тебе сосредоточиться?", en: "What kind of music helps you focus?" },
    { ru: "Какой праздник ты бы устроил(а) без повода?", en: "What celebration would you host for no reason?" },
    { ru: "Какой десерт стоит разделить, а какой — точно нет?", en: "Which dessert is worth sharing, and which definitely is not?" },
    { ru: "Какой предмет делает любое место уютнее?", en: "Which object makes any place feel cosier?" },
    { ru: "Что приятнее получить: длинное сообщение или внезапный звонок?", en: "What feels nicer to receive: a long message or a surprise call?" },
    { ru: "Какой навык ты хотел(а) бы освоить просто для удовольствия?", en: "Which skill would you learn just for fun?" },
    { ru: "Какое блюдо ты любишь готовить для других?", en: "Which dish do you enjoy making for other people?" },
    { ru: "Какое место лучше всего подходит для серьёзного разговора?", en: "Which place is best for an important conversation?" },
    { ru: "Какой совместный план никогда не надоедает?", en: "Which plan together never gets old?" },
    { ru: "Что ты скорее выберешь в свободный вечер прямо сейчас?", en: "What would you choose for a free evening right now?" },
  ],
  hypothetical: [
    { ru: "Если бы завтра был полностью свободный день, что бы мы сделали?", en: "If tomorrow were completely free, what would we do?" },
    { ru: "Куда бы ты телепортировался(-ась) на один вечер?", en: "Where would you teleport for one evening?" },
    { ru: "Какую эпоху ты бы посетил(а) на сутки?", en: "Which era would you visit for one day?" },
    { ru: "Если бы можно было остановить время на час, как бы ты его провёл(а)?", en: "If you could stop time for an hour, how would you spend it?" },
    { ru: "Какой вымышленный дом ты бы выбрал(а) для жизни?", en: "Which fictional home would you choose to live in?" },
    { ru: "Если бы деньги не были важны год, чему бы ты учился(-ась)?", en: "If money did not matter for a year, what would you learn?" },
    { ru: "Какое животное стало бы лучшим собеседником, если бы умело говорить?", en: "Which animal would be the best conversationalist if it could talk?" },
    { ru: "Если бы можно было сохранить один возраст навсегда, какой?", en: "If you could keep one age forever, which one?" },
    { ru: "Какое изобретение из будущего ты бы принёс(ла) домой?", en: "Which future invention would you bring home?" },
    { ru: "Если бы мы открыли маленькое кафе, каким бы оно было?", en: "If we opened a tiny café, what would it be like?" },
    { ru: "Какой день можно было бы повторять раз в год?", en: "Which day would be worth repeating once a year?" },
    { ru: "Если бы у тебя был дополнительный час каждый день, куда бы он уходил?", en: "If you had an extra hour every day, where would it go?" },
    { ru: "Какой талант можно мгновенно получить на одну неделю?", en: "Which talent would you instantly borrow for one week?" },
    { ru: "Если бы твоя жизнь получила название главы, каким оно было бы сейчас?", en: "If your life had a chapter title, what would it be right now?" },
    { ru: "Какой знакомый момент ты хотел(а) бы увидеть глазами другого человека?", en: "Which familiar moment would you like to see through someone else's eyes?" },
    { ru: "Если бы можно было задать один вопрос себе через десять лет, какой?", en: "If you could ask your future self one question, what would it be?" },
    { ru: "Как выглядел бы наш идеальный дом на колёсах?", en: "What would our ideal home on wheels look like?" },
    { ru: "Если бы выходные длились три дня, чему отдать третий?", en: "If weekends lasted three days, what would the third be for?" },
    { ru: "Какую одну вещь ты бы убрал(а) из современного мира?", en: "Which one thing would you remove from modern life?" },
    { ru: "Какой фильм ты хотел(а) бы пережить как реальность на два часа?", en: "Which movie would you experience as reality for two hours?" },
    { ru: "Если бы мы могли оставить послание людям через сто лет, что написать?", en: "If we could leave a note for people a century from now, what would it say?" },
    { ru: "Какую традицию мы могли бы придумать с нуля?", en: "Which tradition could we invent from scratch?" },
    { ru: "Если бы твоя комната могла менять вид по команде, что бы ты выбрал(а)?", en: "If your room could transform on command, what would you choose?" },
    { ru: "Какую планету стоило бы посетить ради одного снимка?", en: "Which planet would be worth visiting for one photograph?" },
    { ru: "Если бы можно было навсегда решить одну бытовую проблему, какую?", en: "Which everyday inconvenience would you solve forever?" },
    { ru: "Какой день мы устроили бы, если бы нельзя было пользоваться экранами?", en: "What day would we plan if screens were not allowed?" },
    { ru: "Если бы одна твоя мечта исполнилась завтра, какую выбрать?", en: "If one dream came true tomorrow, which would you choose?" },
    { ru: "Какой музей ты бы создал(а), если тема может быть любой?", en: "Which museum would you create if the theme could be anything?" },
    { ru: "Если бы пришлось жить внутри одной фотографии, какую бы ты выбрал(а)?", en: "If you had to live inside one photograph, which would you choose?" },
    { ru: "Какая маленькая роскошь стала бы бесплатной для всех в твоём мире?", en: "Which small luxury would be free for everyone in your world?" },
  ],
  deep: [
    { ru: "Когда ты чувствуешь, что тебя действительно понимают?", en: "When do you feel truly understood?" },
    { ru: "Что для тебя означает ощущение дома?", en: "What does feeling at home mean to you?" },
    { ru: "Какую свою черту ты научился(-ась) ценить?", en: "Which part of yourself have you learned to appreciate?" },
    { ru: "Что помогает тебе снова почувствовать опору?", en: "What helps you feel grounded again?" },
    { ru: "Как выглядит забота, которую ты замечаешь сразу?", en: "What kind of care do you notice immediately?" },
    { ru: "Какое решение изменило тебя сильнее, чем ожидалось?", en: "Which decision changed you more than expected?" },
    { ru: "Что ты хотел(а) бы чаще говорить близким людям?", en: "What would you like to say to people close to you more often?" },
    { ru: "В какой момент ты особенно гордился(-ась) собой?", en: "When did you feel especially proud of yourself?" },
    { ru: "Какая поддержка тебе нужна в трудный день?", en: "What kind of support do you need on a hard day?" },
    { ru: "Что тебе стало легче принимать с возрастом?", en: "What has become easier to accept with age?" },
    { ru: "Как ты понимаешь, что человеку можно доверять?", en: "How do you know someone can be trusted?" },
    { ru: "Какой разговор ты вспоминаешь с благодарностью?", en: "Which conversation do you remember with gratitude?" },
    { ru: "Что ты хотел(а) бы защищать в своей жизни сильнее?", en: "What would you like to protect more fiercely in your life?" },
    { ru: "Какая перемена сначала пугала, а потом помогла?", en: "Which change felt scary at first but later helped you?" },
    { ru: "Что для тебя значит быть рядом по-настоящему?", en: "What does truly being there for someone mean to you?" },
    { ru: "Какой комплимент тебе было особенно важно услышать?", en: "Which compliment mattered most for you to hear?" },
    { ru: "В чём ты сейчас учишься быть терпеливее к себе?", en: "Where are you learning to be more patient with yourself?" },
    { ru: "Какое воспоминание напоминает, что всё может стать лучше?", en: "Which memory reminds you that things can get better?" },
    { ru: "Что для тебя важнее всего в долгой дружбе?", en: "What matters most to you in a lasting friendship?" },
    { ru: "Когда тебе легче всего быть собой?", en: "When is it easiest for you to be yourself?" },
    { ru: "Какой страх ты уже перерос(ла)?", en: "Which fear have you already outgrown?" },
    { ru: "Что ты считаешь тихим признаком счастья?", en: "What do you consider a quiet sign of happiness?" },
    { ru: "Какую границу тебе было важно научиться обозначать?", en: "Which boundary was important for you to learn to set?" },
    { ru: "Что делает из обычного места безопасное?", en: "What makes an ordinary place feel safe?" },
    { ru: "Какой урок ты хотел(а) бы усвоить раньше?", en: "Which lesson do you wish you had learned earlier?" },
    { ru: "Как ты предпочитаешь мириться после ссоры?", en: "How do you prefer to reconnect after an argument?" },
    { ru: "Что ты хочешь сохранить неизменным, даже когда жизнь меняется?", en: "What do you want to keep unchanged even as life changes?" },
    { ru: "Какое качество в людях даёт тебе надежду?", en: "Which quality in people gives you hope?" },
    { ru: "Что тебе хотелось бы понять о себе лучше?", en: "What would you like to understand better about yourself?" },
    { ru: "Каким маленьким поступком можно показать большую любовь?", en: "Which small act can show a great deal of love?" },
  ],
  romantic: [
    { ru: "Какой наш обычный момент тебе особенно дорог?", en: "Which ordinary moment of ours feels especially precious?" },
    { ru: "Как я могу сделать твой сложный день чуть легче?", en: "How can I make a difficult day a little easier for you?" },
    { ru: "Какое маленькое совместное приключение устроим следующим?", en: "Which small adventure should we have next?" },
    { ru: "Когда рядом со мной ты чувствуешь себя спокойнее всего?", en: "When do you feel calmest with me?" },
    { ru: "Какой наш разговор хочется запомнить надолго?", en: "Which conversation of ours would you like to remember for a long time?" },
    { ru: "Какой комплимент от меня тебе особенно приятно слышать?", en: "Which compliment from me do you especially like hearing?" },
    { ru: "Как выглядит идеальное маленькое свидание без подготовки?", en: "What does a perfect low-effort date look like?" },
    { ru: "Какой момент заставил тебя почувствовать нашу близость?", en: "Which moment made you feel close to me?" },
    { ru: "Что из наших различий тебе особенно нравится?", en: "Which of our differences do you especially like?" },
    { ru: "Какой совместный ритуал нам стоит завести?", en: "Which shared ritual should we start?" },
    { ru: "Куда ты хотел(а) бы однажды поехать вместе?", en: "Where would you like us to travel together one day?" },
    { ru: "Что во мне тебя до сих пор приятно удивляет?", en: "What about me still pleasantly surprises you?" },
    { ru: "Какой вечер вдвоём ты считаешь идеальным?", en: "What does your ideal evening together look like?" },
    { ru: "Как лучше всего показать тебе, что я слушаю?", en: "What is the best way to show you I am listening?" },
    { ru: "Какую нашу фотографию ты любишь больше всего и почему?", en: "Which photo of us do you love most, and why?" },
    { ru: "Какой запах, вкус или звук ассоциируется у тебя со мной?", en: "Which smell, taste, or sound makes you think of me?" },
    { ru: "Что нам обязательно нужно попробовать вместе впервые?", en: "What should we definitely try together for the first time?" },
    { ru: "Какой момент нашего знакомства ты видишь особенно ясно?", en: "Which moment from when we met do you remember most clearly?" },
    { ru: "Что делает наши тихие моменты особенными?", en: "What makes our quiet moments special?" },
    { ru: "Какую записку от меня тебе хотелось бы найти утром?", en: "What kind of note from me would you love to find in the morning?" },
    { ru: "Какое совместное достижение тебя особенно радует?", en: "Which shared achievement makes you especially happy?" },
    { ru: "Какой день с нами ты бы повторил(а) без изменений?", en: "Which day of ours would you repeat exactly as it was?" },
    { ru: "Что помогает тебе чувствовать себя любимым(-ой)?", en: "What helps you feel loved?" },
    { ru: "Какой сюрприз от меня был бы сейчас самым приятным?", en: "Which surprise from me would feel best right now?" },
    { ru: "Какой общий план на будущее тебя согревает?", en: "Which shared plan for the future makes you feel warm?" },
    { ru: "Как ты любишь получать поддержку именно от меня?", en: "How do you like receiving support specifically from me?" },
    { ru: "Какую песню можно считать нашей прямо сейчас?", en: "Which song could be ours right now?" },
    { ru: "Что нам стоит делать чаще просто ради радости?", en: "What should we do more often just for joy?" },
    { ru: "Какая моя привычка кажется тебе милой?", en: "Which habit of mine do you find sweet?" },
    { ru: "Что ты больше всего ценишь в том, как мы общаемся?", en: "What do you value most about the way we communicate?" },
  ],
  nsfw: [
    { ru: "О чём тебе хотелось бы говорить со мной смелее?", en: "What would you like to talk about more boldly with me?" },
    { ru: "Что помогает тебе чувствовать близость и безопасность?", en: "What helps you feel close and safe?" },
    { ru: "Какой флирт тебе нравится больше всего?", en: "What kind of flirting do you enjoy most?" },
    { ru: "Как ты любишь показывать, что человек тебе очень нравится?", en: "How do you like showing that you are very attracted to someone?" },
    { ru: "Какая атмосфера помогает тебе расслабиться и быть смелее?", en: "Which atmosphere helps you relax and feel bolder?" },
    { ru: "Как понять без слов, что момент подходит?", en: "How can you tell without words that the moment feels right?" },
    { ru: "Какой комплимент заставляет тебя краснеть?", en: "Which compliment makes you blush?" },
    { ru: "Что делает прикосновение особенно нежным для тебя?", en: "What makes a touch feel especially tender to you?" },
    { ru: "Что важнее для настроения: спонтанность или ожидание?", en: "What matters more for the mood: spontaneity or anticipation?" },
    { ru: "Какой романтический жест кажется тебе самым притягательным?", en: "Which romantic gesture feels most attractive to you?" },
    { ru: "О какой границе или желании важно говорить заранее?", en: "Which boundary or wish is important to discuss beforehand?" },
    { ru: "Что помогает тебе полностью довериться моменту?", en: "What helps you fully trust the moment?" },
    { ru: "Какой образ или наряд ты находишь особенно привлекательным?", en: "Which look or outfit do you find especially attractive?" },
    { ru: "Как ты предпочитаешь начинать разговор о желаниях?", en: "How do you prefer to start a conversation about desires?" },
    { ru: "Какой вид нежности тебе хотелось бы получать чаще?", en: "Which kind of affection would you like more often?" },
    { ru: "Что для тебя делает поцелуй запоминающимся?", en: "What makes a kiss memorable for you?" },
    { ru: "Какую роль для тебя играет юмор в близких моментах?", en: "What role does humour play for you in intimate moments?" },
    { ru: "Какое место кажется тебе неожиданно романтичным?", en: "Which place feels unexpectedly romantic to you?" },
    { ru: "Что помогает переключиться с забот дня на близость?", en: "What helps you shift from daily worries into closeness?" },
    { ru: "Какой вопрос о твоих предпочтениях мне стоит задать?", en: "Which question about your preferences should I ask?" },
    { ru: "Как выглядит идеальное медленное утро вдвоём?", en: "What does an ideal slow morning together look like?" },
    { ru: "Что ты считаешь самым важным после очень близкого момента?", en: "What matters most to you after a very intimate moment?" },
    { ru: "Какой неожиданный комплимент тебе хотелось бы услышать?", en: "Which unexpected compliment would you like to hear?" },
    { ru: "Что делает инициативу особенно приятной для тебя?", en: "What makes someone taking initiative feel especially good to you?" },
    { ru: "Какой сигнал означает для тебя уверенное «да»?", en: "Which signal means a confident yes to you?" },
    { ru: "Как лучше проверить, комфортно ли тебе, не разрушая настроение?", en: "How can someone check your comfort without breaking the mood?" },
    { ru: "Что звучит привлекательнее: сюрприз или заранее выбранный план?", en: "What sounds more appealing: a surprise or a plan chosen together?" },
    { ru: "Какой общий секрет мог бы сделать нас ближе?", en: "Which shared secret could make us feel closer?" },
    { ru: "Что тебе нравится в медленном флирте?", en: "What do you enjoy about slow-building flirtation?" },
    { ru: "Какой разговор помог бы нам лучше понимать желания друг друга?", en: "Which conversation would help us understand each other's desires better?" },
  ],
};
