import { StyleSheet } from "react-native";

export const attachmentSheetStyles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  sheet: { overflow: "hidden", borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  header: { height: 57, flexDirection: "row", alignItems: "center", paddingHorizontal: 14 },
  handle: { position: "absolute", width: 36, height: 4, borderRadius: 2, top: 7, left: "50%", marginLeft: -18, opacity: 0.5 },
  title: { flex: 1, marginTop: 5, fontSize: 18, fontWeight: "800" },
  hqButton: { minWidth: 50, height: 32, marginTop: 5, paddingHorizontal: 13, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, alignItems: "center", justifyContent: "center" },
  hqButtonText: { fontSize: 13, fontWeight: "900", letterSpacing: 0.4 },
  grid: { paddingTop: 1 },
  gridList: { flex: 1 },
  gridRow: { gap: 2 },
  uploadTile: { marginBottom: 2, alignItems: "center", justifyContent: "center", paddingHorizontal: 10, gap: 8 },
  uploadIcon: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center" },
  uploadLabel: { textAlign: "center", fontSize: 13, lineHeight: 16, fontWeight: "700" },
  assetTile: { marginBottom: 2, overflow: "hidden", borderWidth: 2, backgroundColor: "#11151a" },
  videoBadge: { position: "absolute", left: 6, bottom: 5, flexDirection: "row", alignItems: "center", gap: 3, paddingHorizontal: 5, height: 20, borderRadius: 10, backgroundColor: "rgba(0,0,0,0.62)" },
  videoDuration: { color: "white", fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"] },
  assetPending: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.42)" },
  selectionBadge: { position: "absolute", top: 6, right: 6, minWidth: 24, height: 24, paddingHorizontal: 5, borderRadius: 12, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "white" },
  selectionNumber: { color: "white", fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
  loading: { height: 52, alignItems: "center", justifyContent: "center" },
  qualityToast: { position: "absolute", alignSelf: "center", maxWidth: "84%", minHeight: 38, paddingHorizontal: 16, borderRadius: 19, alignItems: "center", justifyContent: "center", elevation: 6 },
  qualityToastText: { fontSize: 13, lineHeight: 17, fontWeight: "700", textAlign: "center" },
  sendBar: { minHeight: 64, borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, paddingTop: 8 },
  sendButton: { height: 46, borderRadius: 23, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 },
  sendText: { color: "white", fontSize: 15, fontWeight: "800" },
  sendCount: { minWidth: 24, height: 24, paddingHorizontal: 6, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.22)", alignItems: "center", justifyContent: "center" },
  sendCountText: { color: "white", fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
  busy: { position: "absolute", left: 0, right: 0, bottom: 0, minHeight: 86, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingTop: 10, paddingHorizontal: 18, gap: 12, opacity: 0.96 },
  busyText: { fontSize: 13 },
  cancelUpload: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  progressLabel: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center" },
  progressText: { fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"] },
});
